version: '3.8'

services:
   postgres:
      container_name: trackitPostgresContainer
      image: postgres:14.1
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: postgres
      ports:
         - 5435:5432
